# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 500)
        self.detectDisplayLab = QtWidgets.QLabel(Form)
        self.detectDisplayLab.setGeometry(QtCore.QRect(40, 20, 416, 416))
        self.detectDisplayLab.setText("")
        self.detectDisplayLab.setScaledContents(False)
        self.detectDisplayLab.setObjectName("detectDisplayLab")
        self.openCameraBtn = QtWidgets.QPushButton(Form)
        self.openCameraBtn.setGeometry(QtCore.QRect(50, 450, 100, 30))
        self.openCameraBtn.setAutoRepeatDelay(300)
        self.openCameraBtn.setObjectName("openCameraBtn")
        self.openImageBtn = QtWidgets.QPushButton(Form)
        self.openImageBtn.setGeometry(QtCore.QRect(200, 450, 100, 30))
        self.openImageBtn.setObjectName("openImageBtn")
        self.openVideoBtn = QtWidgets.QPushButton(Form)
        self.openVideoBtn.setGeometry(QtCore.QRect(350, 450, 100, 30))
        self.openVideoBtn.setObjectName("openVideoBtn")

        self.retranslateUi(Form)
        self.openCameraBtn.clicked.connect(Form.open_camera_click)
        self.openVideoBtn.clicked.connect(Form.open_video_click)
        self.openImageBtn.clicked.connect(Form.open_image_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "口罩佩戴识别检测系统"))
        self.openCameraBtn.setText(_translate("Form", "打开摄像头"))
        self.openImageBtn.setText(_translate("Form", "打开图片"))
        self.openVideoBtn.setText(_translate("Form", "打开视频"))
